Add glinter checks to burnham
mozilla/burnham pull request #300
Opened 2021-10-28 13:57 UTC by wlach

This will be useful once https://github.com/mozilla/burnham/pull/299
lands, and we want to enforce the use of tags in burnham.

2021-11-01 14:26 UTC, hackebrot commented
Hi @wlach! 👋🏻 I'm back from PTO. Thank you for submitting this pull request.

2021-11-02 08:10 UTC, hackebrot requested changes
This is great! Thank you @wlach. 🚀 

I've added one inline comment with a suggestion.

2021-11-02 08:10 UTC, hackebrot commented on application/tox.ini
> +    pip-sync {toxinidir}/requirements.txt {toxinidir}/dev-requirements.txt
Since `glean-parser` is installed via `glean-sdk` which is a direct dependency of burnham (see [requirements.txt](https://github.com/mozilla/burnham/blob/5b1360eee6fdf53bd5edfa99d5d5b0d37692b26a/application/requirements.txt#L77-L80)) we can remove this and rely on the default `tox` behavior for installing the package in test environments:

```suggestion
```

2021-11-02 11:50 UTC, wlach commented on application/tox.ini
> +    pip-sync {toxinidir}/requirements.txt {toxinidir}/dev-requirements.txt
Hmm, I seem to remember needing to add this, but maybe I'm misremembering. Let's try it!

2021-11-02 12:04 UTC, hackebrot commented
My apologies @wlach, I'm afraid we do need to explicitly install burnham and its dependencies because we set `skip_install = True` on all tox testenvs. My suggestion worked locally because we also set `isolated_build = False`.

This should do:

```ini
[testenv:glinter]
commands_pre =
    # Install the pinned burnham requirements
    pip-sync {toxinidir}/requirements.txt
```

2021-11-02 12:39 UTC, hackebrot approved these changes
LGTM! 🚀

2021-11-02 12:40 UTC, wlach commented
> LGTM! 🚀

Awesome! I'll leave it to you to merge whenever ready. Would be good to have this in before #299 is up for review (hopefully soon)

2021-11-02 12:41 UTC, merged