Fixes #413: Update python version.
mozilla/burnham pull request #425
Opened 2022-06-02 23:10 UTC by jrbenny35

Updates the burnham application to python 3.10(.4)

2022-06-08 10:11 UTC, hackebrot requested changes
Thank you for this pull request @jrbenny35!

Please upgrade *burnham-bigquery* as well. 📦

2022-06-13 17:13 UTC, hackebrot requested changes
Hi @jrbenny35! 👋🏻 

I've added my comments inline. Did you try out building the Docker images locally?

2022-06-13 17:13 UTC, hackebrot commented on application/setup.py
> +    python_requires=">=3.10",
We don't need to drop support for Python 3.7 - Python 3.9 until we're using Python 3.10+ features. I suggest reverting this particular change.

2022-06-13 17:13 UTC, hackebrot commented on application/setup.py
> +        "Programming Language :: Python :: 3.10",
See above comment.

You can add multiple classifiers for the programming language like this https://github.com/hackebrot/labels/blob/main/setup.py#L40-L41

2022-06-13 17:13 UTC, hackebrot commented on bigquery/requirements.txt
> +pytest==6.2.5
Can you speak to these changes? Are these upgrades required for Python 3.10?

2022-06-13 17:21 UTC, jrbenny35 commented on bigquery/requirements.txt
> +pytest==6.2.5
Yes both of these are needed

2022-06-13 20:01 UTC, jrbenny35 commented
I did build and test the images locally.

2022-06-14 09:38 UTC, hackebrot commented on bigquery/requirements.txt
> +pytest==6.2.5
Ok, thanks!

2022-06-14 19:20 UTC, jrbenny35 commented on application/setup.py
> +    python_requires=">=3.10",
Got it. I just did a hard 3.10 as it doesn't seem like we were going to miss anything but I will keep that in mind in the future.

2022-06-14 19:25 UTC, jrbenny35 commented on application/setup.py
> +        "Programming Language :: Python :: 3.10",
So should I include 3.8, 3.9, 3.10 or just 3.8 and 3.10 and add a test specific for them both?

2022-06-17 09:10 UTC, hackebrot commented on application/setup.py
> +        "Programming Language :: Python :: 3.10",
That depends on what you put for `python_requires`.

My suggestion is `python_requires=">=3.8"` and then it's:

```
"Programming Language :: Python :: 3.8",
"Programming Language :: Python :: 3.9",
"Programming Language :: Python :: 3.10",
```

Then if you can decide if you want to add `py38` and `py39` to the tox config, so that we run `pytest` for supported Python versions. I'd say this is optional given that we're only using Python 3.10 in practice.

2022-06-17 19:00 UTC, jrbenny35 commented
So I added tests and circleci changes to support the tests as well.

2022-06-23 09:07 UTC, hackebrot commented on .circleci/config.yml
> +              tox_env: ["black", "flake8", "mypy", "glinter", "py310", "py39", "py38"]
Have you considered configuring multiple jobs using different Docker images for the different Python versions instead of one Docker image that has all of the required Python versions installed?

| Docker | tox_env | 
| -------------- | -------- |
|`image: python:3.10`|`["black", "flake8", "mypy", "glinter", "py310"]`|
|`image: python:3.8`|`["py38"]`|
|`image: python:3.9`|`["py39"]`|

This way we can continue to use the official Python Docker images for the checks and the application.

2022-06-23 09:14 UTC, hackebrot commented on application/tox.ini
> +[testenv:py310]
We can probably use one generic `testenv` that `["py38", "py39", "py310"]` use, so we don't have to duplicate the configuration.

You can try that out by merging the `[testenv:py310]` config into to `[testenv]` and checking that the other environments `black, flake8, mypy, glinter` overwrite the `py310` specific `commands_pre` and `commands` commands.

2022-06-23 09:18 UTC, hackebrot commented on application/tox.ini
> +ignore_basepython_conflict = True
Please add an inline comment about what this does and what that means for `basepython` and implied Python versions for test environments.

2022-06-27 16:03 UTC, jrbenny35 commented on .circleci/config.yml
> +      - image: fkrull/multi-python
Well, in my opinion, it is a pretty simple script. Not really much maintenance needed, but I did have to add the extra steps you saw. Only thing of concern would be the base image but that wouldn't be hard to update. I was trying to keep the way things are now with using 1 simple image instead of having multiple images and jobs. If I cloned and supported this image would that ease some of your concerns?

2022-06-27 18:03 UTC, hackebrot commented on .circleci/config.yml
> +      - image: fkrull/multi-python
As I've mentioned in an earlier review on this pull request (https://github.com/mozilla/burnham/pull/425#discussion_r899929892), I consider running the tests under Python 3.8 and 3.9 optional given that we're only using Python 3.10 in practice.

I don't think it's worth adding the complexity and effort of maintaining a non-official Docker image or a series of apt-get commands to this project. I'd say either use the other official Python images (which are likely to be cached on CircleCI) or only run tests with Python 3.10 only. Running the tests with the same (or similar) image than the one we actually use for running the application is important.

2022-06-27 19:38 UTC, jrbenny35 commented
Alright, I removed all my attempts at testing against multiple versions.

2022-06-29 09:45 UTC, hackebrot requested changes

2022-07-12 11:17 UTC, hackebrot approved these changes
LGTM! 🚀

2022-07-12 11:17 UTC, merged