Initial commit adding dependabot.
mozilla/burnham pull request #78
Opened 2020-09-30 21:21 UTC by jrbenny35

Closes #67

2020-09-30 21:43 UTC, jklukas reviewed
I think the scope of this PR should include using the requirements.txt in `application/Dockerfile` for determining which specific dependencies are included in the published docker container. Or would you prefer to break that out to a separate PR?

This looks good except that I was expecting the `requirements.txt` to appear under the `application` folder. This repo contains two separate logical applications (application/ and bigquery/), and I think we want to keep their dependencies separate.

2020-09-30 21:43 UTC, jklukas commented on dependabot.yml
> +      interval: "weekly"
We may want to make this daily to shorten the time between a new glean sdk version being published and it being exercised by burnham.

2020-09-30 22:05 UTC, jrbenny35 commented
> I think the scope of this PR should include using the requirements.txt in `application/Dockerfile` for determining which specific dependencies are included in the published docker container. Or would you prefer to break that out to a separate PR?
> 

These requirements were taken from the 4 in ```applications/setup.py``` the ```install_requires```. I can move the file over though, I agree it should not exist at ```/```

2020-10-01 07:57 UTC, hackebrot reviewed
I agree with @jklukas, we can include updating `application/Docker` to install from `application/requirements.txt` in this pull-request. 🤖

2020-10-01 07:57 UTC, hackebrot commented on dependabot.yml
> +    directory: "/"
Do we need to update this to point to `application/` now that you moved the file?

2020-10-02 15:29 UTC, hackebrot requested changes
Please modify `application/Docker` to create wheels from `application/requirements.txt` and make sure the correct packages are installed when creating the container.

2020-10-02 15:29 UTC, hackebrot commented on application/setup.py
> +    install_requires=[],
We still need to define direct dependencies for burnham here.

2020-10-02 15:29 UTC, hackebrot commented on dependabot.yml
> +      interval: "weekly"
Please update the `interval` as per @jklukas's suggestion.

2020-10-02 16:35 UTC, jklukas commented on application/setup.py
> +    install_requires=[],
It does get kind of confusing what to put where when you have both `install_requires` and `requirements.txt`. What I've seen is that `install_requires` defines minimal dependencies without pinning versions, so that if another project were importing this as a library, it would be flexible. And then requirements.txt has everything pinned for maximum stability of CI and published docker images.

So I think this line can stay as it currently exists in `main`.

2020-10-02 16:46 UTC, hackebrot commented on application/setup.py
> +    install_requires=[],
> So I think this line can stay as it currently exists in main.

Yes, I agree. 👍

2020-10-02 18:27 UTC, jrbenny35 commented on application/setup.py
> +    install_requires=[],
I'm not sure I follow. I thought if you have a requirements file you don't need to specify dependencies here.

2020-10-02 18:42 UTC, jklukas commented on application/setup.py
> +    install_requires=[],
> I thought if you have a requirements file you don't need to specify dependencies here.

That is technically true in this case because `burnham` isn't published as a library. It's still nice to include `install_requires` as a form of documentation, though, as it captures the logical dependencies without the noise of the transitive dependencies and pinned versions.

That said, there is the downside that we could well end up adding new dependencies in requirements and forget to update the list here, so it could become stale.

2020-10-05 17:46 UTC, hackebrot commented on application/setup.py
> +    install_requires=[],
We list direct dependencies for burnham in `install_requires` because we know that burnham cannot work without these packages. We import from these specific packages and rely on the APIs to be available.

```python
install_requires=["click>=7.0", "glean-sdk>=32.3.1", "wrapt", "typing_extensions"]
```

We don't necessarily specify a version range for the direct dependencies, as long as we know that a certain feature became available in a specific version or that an API we rely on is deprecated and will be removed in a future release of that dependency. We also don't specify the dependencies of direct dependencies, because those are internal details of our dependencies.

The purpose of pinning versions for direct dependencies and transitive dependencies in a `requirements.txt` file is reproducibility (aside from making it easier to integrate Dependabot). When we install from this file, we know exactly which packages are installed and given that we pin dependencies, we also know which version is installed when we run the burnham application.

We expect the packages listed as dependencies in `install_requires` to be available after installing from `requirements.txt`. If we don't specify `install_requires`, we lose the error reporting at the installation stage and will only find out when running burnham that we are missing a dependency.

In summary, `install_requires` is important for installing the burnham package and its direct dependencies and `requirements.txt` is important for making sure we know exactly which packages and versions are installed when building the burnham Docker image and running that in our test runs.

Hope this helps!

2020-10-05 19:45 UTC, jklukas commented on application/Dockerfile
> +RUN python -m pip wheel -w /wheels -r requirements.txt
```suggestion
RUN python -m pip wheel -w /wheels -r requirements.txt
RUN python -m pip wheel -w /wheels .
```

I believe we still need to instruct `pip` to install the local package. It's possible we could do this all in one invocation, or by adding `.` to the `requirements.txt` file, but I think two separate invocations is the clearest way to express the intent.

I think this is the only remaining detail. Otherwise, this PR is looking great!

2020-10-05 20:45 UTC, jrbenny35 commented on application/Dockerfile
> +RUN python -m pip wheel -w /wheels -r requirements.txt
Ah yes, thanks for pointing this out

2020-10-05 20:59 UTC, jklukas approved these changes
r+ with comment

This just needs to have the `RUN python -m pip wheel -w /wheels .` line added. You can either do that locally and push your changes, or you can use the "Commit suggestion" dropdown on https://github.com/mozilla/burnham/pull/78/files#r499831296.

2020-10-05 21:12 UTC, jrbenny35 commented
> r+ with comment
> 
> This just needs to have the `RUN python -m pip wheel -w /wheels .` line added. You can either do that locally and push your changes, or you can use the "Commit suggestion" dropdown on https://github.com/mozilla/burnham/pull/78/files#r499831296.

I added that. Can you double-check? I can see it

2020-10-06 08:14 UTC, hackebrot commented
The `RUN python -m pip wheel -w /wheels .` line doesn't show as an addition in the diff because it's already on the `main` branch. I can see it in the file on Ben's branch.

2020-10-06 09:00 UTC, hackebrot commented
I was chatting with @jezdez about pip wheel today and he suggested to combine the two `RUN python -m pip wheel -w /wheels` steps into one by using only `RUN python -m pip wheel -w /wheels -r requirements.txt` and adding `.` to `requirements.txt`. This has the benefit of allowing pip to resolve to one dependency tree and generating wheels in one step. I think that makes a lot of sense and suggest we follow this approach! 📦

2020-10-06 13:02 UTC, jklukas commented on application/Dockerfile
> +RUN python -m pip wheel -w /wheels -r requirements.txt
Per @jezdez suggestion in https://github.com/mozilla/burnham/pull/78#issuecomment-704132772
```suggestion
RUN python -m pip wheel -w /wheels -r requirements.txt .
```

2020-10-06 13:03 UTC, jklukas commented on application/Dockerfile
>  RUN python -m pip wheel -w /wheels .
```suggestion
RUN python -m pip wheel -w /wheels -r requirements.txt .
```

2020-10-06 13:07 UTC, jklukas commented on application/Dockerfile
>  RUN python -m pip wheel -w /wheels .
```suggestion
RUN python -m pip wheel -w /wheels -r requirements.txt .
```

2020-10-06 13:08 UTC, jklukas commented
Sorry. I inadvertently committed a bad suggestion to this branch. I then backed it out.

Once we commit the suggestion to go down to a single `pip` invocation, this is good to merge.

2020-10-06 15:51 UTC, jrbenny35 commented on application/Dockerfile
>  RUN python -m pip wheel -w /wheels .
This is what I had originally but it continues the ```-r``` and tries installing the dir as a requirement.

2020-10-07 07:44 UTC, hackebrot requested changes
Added a few comments. 📝

2020-10-07 07:44 UTC, hackebrot commented on application/Dockerfile
>  RUN python -m pip wheel -w /wheels .
I’m getting an error for `RUN python -m pip wheel -w /wheels -r requirements.txt .` when I try this locally:

```text
ERROR: Can’t verify hashes for these file:// requirements because they point to directories:
    file:///usr/src/burnham
```

Looks like we cannot combine a requirements file that contains hashes and a local directory.

I suggest we use the following two steps:

```text
RUN python -m pip wheel -w /wheels -r requirements.txt
RUN python -m pip wheel -w /wheels —no-deps .
```

This way we install the packages in the requirements file with hashes and build wheels for them and then build a wheel only for burnham in the next step.

2020-10-07 07:44 UTC, hackebrot commented on dependabot.yml
> +      interval: "daily"
Please add the newline at the end of the file.

2020-10-07 07:44 UTC, hackebrot commented on dependabot.yml
> +version: 2
Do we need to enable Dependabot in the repo settings? Or is adding this file enough to enable it?

2020-10-07 07:44 UTC, hackebrot commented on application/requirements.txt
> +appdirs==1.4.4 \
Which tool did you use to generate this file?

2020-10-07 12:06 UTC, jezdez commented on application/requirements.txt
> +appdirs==1.4.4 \
I recommend using pip-tools' pip-compile for generating this file, which has been used in Mozilla for a while and [recommended elsewhere](https://hynek.me/articles/python-app-deps-2018/), too.

2020-10-07 12:10 UTC, jezdez commented on application/Dockerfile
>  RUN python -m pip wheel -w /wheels .
Oh wait, that wasn't my recommendation! It was to put `.` **inside** the requirements.txt and not have separate calls to `pip wheel`. pip does the right thing and then first resolves the dependency chain of the `burnham` package in addition to those requirements listed in the requirements file.

The call would just be 

```suggestion
RUN python -m pip wheel --wheel-dir /wheels -r requirements.txt
```

2020-10-07 12:18 UTC, jezdez commented on application/Dockerfile
>  RUN python -m pip wheel -w /wheels .
Hm, unless that doesn't work for requirements files with hashes as @hackebrot said in https://github.com/mozilla/burnham/pull/78#discussion_r500800987. So calling it twice is probably the easiest to do this, sadly.

2020-10-08 18:52 UTC, jrbenny35 commented on application/requirements.txt
> +appdirs==1.4.4 \
I didn't use any tool. Every tool I have used has been annoying and to me it's easier just to copy paste but I will try @jezdez suggestion. Should I re-do them?

2020-10-08 18:53 UTC, jrbenny35 commented on dependabot.yml
> +version: 2
Github docs say ```You enable GitHub Dependabot version updates by checking a configuration file in to your repository. ```, https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/about-github-dependabot-version-updates#about-github-dependabot-version-updates

2020-10-12 08:03 UTC, hackebrot approved these changes
LGTM! 🚀

2020-10-12 08:07 UTC, merged